export const COFFEE_COUNTRIES = [
	{ name: "Brazil", flag: "br" },
	{ name: "Vietnam", flag: "vn" },
	{ name: "Colombia", flag: "co" },
	{ name: "Indonesia", flag: "id" },
	{ name: "Ethiopia", flag: "et" },
	{ name: "Honduras", flag: "hn" },
	{ name: "India", flag: "in" },
	{ name: "Uganda", flag: "ug" },
	{ name: "Mexico", flag: "mx" },
	{ name: "Guatemala", flag: "gt" },
	{ name: "Peru", flag: "pr" },
	{ name: "Nicaragua", flag: "ni" },
	{ name: "China", flag: "cn" },
	{ name: "Ivory Coast", flag: "ci" },
	{ name: "Costa Rica", flag: "cr" },
	{ name: "Kenya", flag: "ke" },
	{ name: "Papua New Guinea", flag: "pg" },
	{ name: "Tanzania", flag: "tz" },
	{ name: "El Salvador", flag: "sv" },
	{ name: "Ecuador", flag: "ec" },
	{ name: "Cameroon", flag: "cm" },
	{ name: "Laos", flag: "la" },
	{ name: "Madagascar", flag: "mg" },
	{ name: "Gabon", flag: "ga" },
	{ name: "Thailand", flag: "th" },
	{ name: "Venezuela", flag: "ve" },
	{ name: "Dominican", flag: "do" },
	{ name: "Haiti", flag: "ht" },
	{ name: "Democratic Republic of the Congo", flag: "cd" },
	{ name: "Rwanda", flag: "rw" },
	{ name: "Burundi", flag: "bi" },
	{ name: "Philippines", flag: "ph" },
	{ name: "Togo", flag: "tg" },
	{ name: "Guinea", flag: "gn" },
	{ name: "Yemen", flag: "ye" },
	{ name: "Cuba", flag: "cu" },
	{ name: "Panama", flag: "pa" },
	{ name: "Bolivia", flag: "bo" },
	{ name: "Timor Leste", flag: "tl" },
	{ name: "Central African Republic", flag: "cf" },
	{ name: "Nigeria", flag: "ng" },
	{ name: "Ghana", flag: "gh" },
	{ name: "Sierra Leone", flag: "sl" },
	{ name: "Angola", flag: "ao" },
	{ name: "Jamaica", flag: "jm" },
	{ name: "Paraguay", flag: "py" },
	{ name: "Malawi", flag: "mw" },
	{ name: "Trinidad and Tobago", flag: "tt" },
	{ name: "Zimbabwe", flag: "zw" },
	{ name: "Liberia", flag: "lr" },
	{ name: "Zambia", flag: "zm" },
];
