export const ASSET_PATH = "/assets/country-autocomplete/";

export const COFFEE_COUNTRIES_CONTINENTS = [
	{
		name: "Africa",
		countries: [
			{ name: "Ethiopia", flag: "et", continent: "Africa" },
			{ name: "Uganda", flag: "ug", continent: "Africa" },
			{ name: "Ivory Coast", flag: "ci", continent: "Africa" },
			{ name: "Kenya", flag: "ke", continent: "Africa" },
			{ name: "Tanzania", flag: "tz", continent: "Africa" },
			{ name: "Cameroon", flag: "cm", continent: "Africa" },
			{ name: "Madagascar", flag: "mg", continent: "Africa" },
			{ name: "Gabon", flag: "ga", continent: "Africa" },
			{
				name: "Democratic Republic of the Congo",
				flag: "cd",
				continent: "Africa",
			},
			{ name: "Rwanda", flag: "rw", continent: "Africa" },
			{ name: "Burundi", flag: "bi", continent: "Africa" },
			{ name: "Togo", flag: "tg", continent: "Africa" },
			{ name: "Guinea", flag: "gn", continent: "Africa" },
			{
				name: "Central African Republic",
				flag: "cf",
				continent: "Africa",
			},
			{ name: "Nigeria", flag: "ng", continent: "Africa" },
			{ name: "Ghana", flag: "gh", continent: "Africa" },
			{ name: "Sierra Leone", flag: "sl", continent: "Africa" },
			{ name: "Angola", flag: "ao", continent: "Africa" },
			{ name: "Malawi", flag: "mw", continent: "Africa" },
			{ name: "Zimbabwe", flag: "zw", continent: "Africa" },
			{ name: "Liberia", flag: "lr", continent: "Africa" },
			{ name: "Zambia", flag: "zm", continent: "Africa" },
		],
	},
	{
		name: "Asia",
		countries: [
			{ name: "Vietnam", flag: "vn" },
			{ name: "Indonesia", flag: "id" },
			{ name: "India", flag: "in" },
			{ name: "China", flag: "cn" },
			{ name: "Laos", flag: "la" },
			{ name: "Thailand", flag: "th" },
			{ name: "Philippines", flag: "ph" },
			{ name: "Yemen", flag: "ye" },
			{ name: "Timor Leste", flag: "tl" },
		],
	},
	{
		name: "Central America",
		countries: [
			{ name: "Honduras", flag: "hn" },
			{ name: "Mexico", flag: "mx" },
			{ name: "Guatemala", flag: "gt" },
			{ name: "Nicaragua", flag: "ni" },
			{ name: "Costa Rica", flag: "cr" },
			{ name: "El Salvador", flag: "sv" },
			{ name: "Dominican", flag: "do" },
			{ name: "Haiti", flag: "ht" },
			{ name: "Cuba", flag: "cu" },
			{ name: "Panama", flag: "pa" },
			{ name: "Jamaica", flag: "jm" },
			{ name: "Trinidad and Tobago", flag: "tt" },
		],
	},
	{
		name: "South America",
		countries: [
			{ name: "Brazil", flag: "br" },
			{ name: "Colombia", flag: "co" },
			{ name: "Peru", flag: "pr" },
			{ name: "Ecuador", flag: "ec" },
			{ name: "Venezuela", flag: "ve" },
			{ name: "Bolivia", flag: "bo" },
			{ name: "Paraguay", flag: "py" },
		],
	},
];
